on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '16.x'
  CI: false

jobs: 
  build-and-deploy:
    name: Build and Deploy
    runs-on: self-hosted
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{evn.NODE_VERSION}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{evn.NODE_VERSION}}
      
      - name: Install Yarn
        run: npm install -g yarn