on:
  push:
    branches:
      - "*"

# env:
#   NODE_VERSION: "16.x"
#   CI: true
#   test: "test"

jobs:
  build-and-deploy:
    name: "Build and Deploy"
    runs-on: [self-hosted, windows, X64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # - name: Use Node.js ${{ env.NODE_VERSION }}
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}
      # - name: Install Yarn
      #   run: npm install -g yarn
      # - name: Run tests
      #   run: |
      #     # Build and test the project, then
      #     yarn install
      #     yarn run test
      #     yarn run lint
      #     yarn run build
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
